services:
  db:
    image: postgres:17-alpine
    container_name: postgresql17
    platform: linux/arm64
    restart: always
    environment:
      - POSTGRES_USER=cal_user
      - POSTGRES_PASSWORD=cal_password
      - POSTGRES_DB=cal_db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cal_user -d cal_db"]
      interval: 5s
      timeout: 5s
      retries: 5